name: block_breakingbad_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_offline: ^2.1.0
  cached_network_image: ^3.2.3
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter_svg: ^1.1.6


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/
    - assets/images/playerimages/
    - assets/icons/
  
  fonts:
    - family: SFProRounded
      fonts:
        - asset: fonts/SF-Pro-Rounded-Medium.otf
          weight: 700 
        - asset: fonts/SF-Pro-Rounded-Medium.otf
          weight: 400 
        - asset: fonts/SF-Pro-Rounded-Medium.otf
          weight: 300 

